sensu-client:
  container_name: sensu-client-faktura
  restart: always
  image: demo/sensu-client-faktura:latest
  net: local_network
  command: client
  environment:
    TRANSPORT_NAME: rabbitmq
    CLIENT_NAME: faktura-host
    CLIENT_ADDRESS: 35.157.234.116
    RABBITMQ_HOST: sensu-rabbitmq
    JENKINS_PREFIX: jenkins
    CLIENT_SUBSCRIPTIONS: "faktura"
    FAKTURA_IP: 35.157.234.116